### ISSUE TITLE
Protocols for Task Submissions

### ISSUE THREAD

**Issue by goldsteinn** [dtcxzyw/llvm-opt-benchmark#1360]
Is there any protocol you want us to follow regarding labeling / closing our submissions?

**Comment by dtcxzyw** [comment]
Done. Tested with https://github.com/dtcxzyw/llvm-opt-benchmark/pull/1356.

**Comment by goldsteinn** [comment]
?

**Comment by goldsteinn** [comment]
Im going to assume no.
