### ISSUE TITLE
Check the final machine code with `llvm-mca`?

### ISSUE THREAD

**Issue by DianQK** [dtcxzyw/llvm-opt-benchmark#139]
I'm not sure how the optimization results are currently checked? It looks like it's by looking at the diff?

But I created this issue because I realized that just checking the LLVM IR may wasn't enough.
Despite providing an IR with more facts, the code gen may submit poor code.

See https://github.com/llvm/llvm-project/issues/78578.

**Comment by dtcxzyw** [comment]
> I'm not sure how the optimization results are currently checked? It looks like it's by looking at the diff?
> 
> But I created this issue because I realized that just checking the LLVM IR may wasn't enough. Despite providing an IR with more facts, the code gen may submit poor code.

You are right. See also our old CI https://github.com/dtcxzyw/llvm-ci.
