### ISSUE TITLE
Output compile-time

### ISSUE THREAD

**Issue by v01dXYZ** [dtcxzyw/llvm-opt-benchmark#680]
Is there a way to output `compile-time` (possibly with multiple runs) ?

If not and if it is relevant, I could submit a PR for that.

**Comment by dtcxzyw** [comment]
Yeah, you can obtain the compilation time with perf: `perf stat -e instructions:u opt ...`.

I am sorry I cannot provide the baseline result for each run because PMU is not accessible on our CI workers.
But I can provide an option then you can run and compare the result locally :)

**Comment by dtcxzyw** [comment]
See https://github.com/dtcxzyw/llvm-opt-benchmark/commit/e286d17e0c81f18c97e12942ccc6e93d88ef7116
Usage:
```
./scripts/gen_optimized.py bench/ <path-to-opt> comptime comptime-v1.log
./scripts/gen_optimized.py bench/ <path-to-new-opt> comptime comptime-v2.log
python3 ./scripts/comptime_diff.py comptime-v1.log comptime-v2.log
```

**Comment by dtcxzyw** [comment]
> See [e286d17](https://github.com/dtcxzyw/llvm-opt-benchmark/commit/e286d17e0c81f18c97e12942ccc6e93d88ef7116) Usage:
> 
> ```
> ./scripts/gen_optimized.py bench/ <path-to-opt> comptime comptime-v1.log
> ./scripts/gen_optimized.py bench/ <path-to-new-opt> comptime comptime-v2.log
> python3 ./scripts/comptime_diff.py comptime-v1.log comptime-v2.log
> ```

I will update the README at my convenience.
