### ISSUE TITLE
Grep pr99245 (Constant)

### ISSUE THREAD

**Issue by dtcxzyw** [dtcxzyw/llvm-opt-benchmark#977]
```
define i32 @src(i32 %a, i32 %b, i32 %x, i32 %cy, i32 %cz, i1 %c2) {
  %cmp1 = icmp slt i32 %x, %cy
  %cmp2 = icmp sgt i32 %x, %cz
  %sel1 = select i1 %cmp1, i32 %a, i32 %b
  %sel2 = select i1 %cmp2, i32 %a, i32 %b
  %ret = select i1 %c2, i32 %sel1, i32 %sel2
  ret i32 %ret
}
```
https://github.com/llvm/llvm-project/pull/99245#discussion_r1680516517

**Comment by goldsteinn** [comment]
Shouldn't it be `slt` / `sge`? But to understand the pattern matching, does this match only the specific predicates, or any pred? Does this only match `i32`?

**Comment by dtcxzyw** [comment]
> Shouldn't it be `slt` / `sge`? But to understand the pattern matching, does this match only the specific predicates, or any pred? Does this only match `i32`?

It doesn't match specific predicates/types/values.
See https://github.com/dtcxzyw/llvm-opt-benchmark/blob/main/daggrep.cpp.
